on:
  workflow_call

jobs:
  setup-vcluster:
    name: "Setup Vcluster"
    runs-on: ubuntu-latest
    if: github.event_name == 'create' && github.ref_type == 'branch'
    steps:
      - name: Setting up Vcluster
        run: echo "Setting up vcluster"
  delete-vcluster:
    name: "Delete Vcluster"
    runs-on: ubuntu-latest
    if: github.event_name == 'delete'
    steps:
      - name: Deleting Vcluster
        run: echo "Deleting up vcluster"
